{
 "title": "ShieldGuard ML Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Predictions Count Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pnc_predictions_total[1m])",
     "legendFormat": "Predictions/sec"
    }
   ]
  },
  {
   "title": "Fraud Detected Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(pnc_fraud_total[1m])", "legendFormat": "Fraud Cases/sec" }
   ]
  },
  {
   "title": "Model Prediction Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pnc_avg_latency_seconds", "legendFormat": "Latency (s)" }
   ]
  }
 ]
}